default_language_version:
  python: python3.9

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  -   id: check-merge-conflict
  -   id: debug-statements
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    args: ['--ignore-missing-imports']
    exclude: tests
    additional_dependencies: [types-requests]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.1
  hooks:
  - id: isort
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.17
  hooks:
  - id: circleci-config-validate
  - id: shellcheck
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
