default_language_version:
  python: python3.7

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  -   id: check-merge-conflict
  -   id: debug-statements
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.760
  hooks:
  - id: mypy
    args: ['--ignore-missing-imports']
    exclude: tests
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.7
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.6
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.16
  hooks:
  - id: circleci-config-validate
  - id: shellcheck
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
