---
dist: bionic
install:
  - docker pull postgres:11
  - docker pull paperlib/kafka:2.3.1
  - pip install -e .[dev]
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
script:
  pytest --cov-report=xml
services:
  - docker

# vim: et:sw=2:syntax=2:ts=2:
