[build-system]
requires = ["setuptools>=65.7.0,<66.0.0", "wheel~=0.38.0", "setuptools_scm[toml]>=7.1.0,<7.2.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/dockerfixtures/version.py"
