[build-system]
requires = ["setuptools>=57.0.0,<58.0.0", "wheel~=0.36.2", "setuptools_scm[toml]>=6.0.0,<7.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/dockerfixtures/version.py"
