[build-system]
requires = ["setuptools>=59.4.0,<60.0.0", "wheel~=0.37.0", "setuptools_scm[toml]>=6.0.0,<7.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/dockerfixtures/version.py"
